//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class obiekty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public obiekty()
        {
            this.trasa_obiekt = new HashSet<trasa_obiekt>();
        }
    
        public int id { get; set; }
        public string nazwa { get; set; }
        public Nullable<int> id_panstwa { get; set; }
        public Nullable<int> id_miasta { get; set; }
        public string ulica { get; set; }
        public Nullable<int> nr_domu { get; set; }
        public Nullable<double> g_szerokosc { get; set; }
        public Nullable<double> g_dlugosc { get; set; }
    
        public virtual miasta miasta { get; set; }
        public virtual panstwa panstwa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trasa_obiekt> trasa_obiekt { get; set; }
    }
}
