//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class trasa_naglowek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trasa_naglowek()
        {
            this.trasa_obiekt = new HashSet<trasa_obiekt>();
        }
    
        public int id { get; set; }
        public string nazwa { get; set; }
        public Nullable<int> id_uzytkownika { get; set; }
        public Nullable<System.DateTime> data_dodania { get; set; }
    
        public virtual uzytkownicy uzytkownicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trasa_obiekt> trasa_obiekt { get; set; }
    }
}
